/**
 * Application-specific error codes for consistent API error responses.
 */
export enum ErrorCode {
  // Auth
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",

  // Validation
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_INPUT = "INVALID_INPUT",

  // Readings
  READING_NOT_FOUND = "READING_NOT_FOUND",
  READING_LIMIT_REACHED = "READING_LIMIT_REACHED",
  INVALID_READING_TYPE = "INVALID_READING_TYPE",

  // Points
  INSUFFICIENT_POINTS = "INSUFFICIENT_POINTS",

  // Friends
  FRIEND_REQUEST_EXISTS = "FRIEND_REQUEST_EXISTS",
  ALREADY_FRIENDS = "ALREADY_FRIENDS",
  FRIEND_REQUEST_NOT_FOUND = "FRIEND_REQUEST_NOT_FOUND",
  CANNOT_FRIEND_SELF = "CANNOT_FRIEND_SELF",
  FRIENDSHIP_NOT_FOUND = "FRIENDSHIP_NOT_FOUND",
  REQUEST_NOT_PENDING = "REQUEST_NOT_PENDING",

  // Arcade
  GAME_NOT_FOUND = "GAME_NOT_FOUND",
  GAME_NOT_ACTIVE = "GAME_NOT_ACTIVE",
  INVALID_GAME_CONFIG = "INVALID_GAME_CONFIG",

  // Stripe
  MISSING_STRIPE_SIGNATURE = "MISSING_STRIPE_SIGNATURE",
  INVALID_STRIPE_SIGNATURE = "INVALID_STRIPE_SIGNATURE",

  // Users
  USER_NOT_FOUND = "USER_NOT_FOUND",

  // Reactions
  ALREADY_REACTED = "ALREADY_REACTED",
  INVALID_EMOJI = "INVALID_EMOJI",

  // Rate limiting
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  // Horoscope
  ZODIAC_SIGN_NOT_SET = "ZODIAC_SIGN_NOT_SET",
  INVALID_ZODIAC_SIGN = "INVALID_ZODIAC_SIGN",
  HOROSCOPE_GENERATION_FAILED = "HOROSCOPE_GENERATION_FAILED",

  // Push
  PUSH_SUBSCRIPTION_EXISTS = "PUSH_SUBSCRIPTION_EXISTS",
  PUSH_SUBSCRIPTION_NOT_FOUND = "PUSH_SUBSCRIPTION_NOT_FOUND",

  // Compatibility
  COMPATIBILITY_GENERATION_FAILED = "COMPATIBILITY_GENERATION_FAILED",

  // Generic
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}
