/**
 * Application-specific error codes for consistent API error responses.
 */
export enum ErrorCode {
  // Auth
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",

  // Validation
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_INPUT = "INVALID_INPUT",

  // Readings
  READING_NOT_FOUND = "READING_NOT_FOUND",
  READING_LIMIT_REACHED = "READING_LIMIT_REACHED",
  INVALID_READING_TYPE = "INVALID_READING_TYPE",

  // Points
  INSUFFICIENT_POINTS = "INSUFFICIENT_POINTS",

  // Friends
  FRIEND_REQUEST_EXISTS = "FRIEND_REQUEST_EXISTS",
  ALREADY_FRIENDS = "ALREADY_FRIENDS",
  FRIEND_REQUEST_NOT_FOUND = "FRIEND_REQUEST_NOT_FOUND",
  CANNOT_FRIEND_SELF = "CANNOT_FRIEND_SELF",
  FRIENDSHIP_NOT_FOUND = "FRIENDSHIP_NOT_FOUND",
  REQUEST_NOT_PENDING = "REQUEST_NOT_PENDING",

  // Arcade
  GAME_NOT_FOUND = "GAME_NOT_FOUND",
  GAME_NOT_ACTIVE = "GAME_NOT_ACTIVE",
  INVALID_GAME_CONFIG = "INVALID_GAME_CONFIG",

  // Stripe
  MISSING_STRIPE_SIGNATURE = "MISSING_STRIPE_SIGNATURE",
  INVALID_STRIPE_SIGNATURE = "INVALID_STRIPE_SIGNATURE",

  // Users
  USER_NOT_FOUND = "USER_NOT_FOUND",
  ACCOUNT_ALREADY_DELETED = "ACCOUNT_ALREADY_DELETED",
  SETTINGS_UPDATE_FAILED = "SETTINGS_UPDATE_FAILED",

  // Reactions
  ALREADY_REACTED = "ALREADY_REACTED",
  INVALID_EMOJI = "INVALID_EMOJI",

  // Rate limiting
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  // Horoscope
  ZODIAC_SIGN_NOT_SET = "ZODIAC_SIGN_NOT_SET",
  INVALID_ZODIAC_SIGN = "INVALID_ZODIAC_SIGN",
  HOROSCOPE_GENERATION_FAILED = "HOROSCOPE_GENERATION_FAILED",

  // Push
  PUSH_SUBSCRIPTION_EXISTS = "PUSH_SUBSCRIPTION_EXISTS",
  PUSH_SUBSCRIPTION_NOT_FOUND = "PUSH_SUBSCRIPTION_NOT_FOUND",

  // Compatibility
  COMPATIBILITY_GENERATION_FAILED = "COMPATIBILITY_GENERATION_FAILED",

  // Referrals
  REFERRAL_CODE_NOT_FOUND = "REFERRAL_CODE_NOT_FOUND",
  CANNOT_REFER_SELF = "CANNOT_REFER_SELF",
  ALREADY_REFERRED = "ALREADY_REFERRED",

  // Gift Readings
  GIFT_NOT_FOUND = "GIFT_NOT_FOUND",
  GIFT_ALREADY_REDEEMED = "GIFT_ALREADY_REDEEMED",

  // Follows
  CANNOT_FOLLOW_SELF = "CANNOT_FOLLOW_SELF",
  ALREADY_FOLLOWING = "ALREADY_FOLLOWING",
  NOT_FOLLOWING = "NOT_FOLLOWING",

  // Comments
  COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND",
  COMMENT_TOO_LONG = "COMMENT_TOO_LONG",

  // Reports
  REPORT_NOT_FOUND = "REPORT_NOT_FOUND",
  DUPLICATE_REPORT = "DUPLICATE_REPORT",

  // Notifications
  NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",

  // Search
  SEARCH_QUERY_REQUIRED = "SEARCH_QUERY_REQUIRED",

  // Arcade daily limits
  DAILY_LIMIT_REACHED = "DAILY_LIMIT_REACHED",

  // Challenges
  CHALLENGE_NOT_FOUND = "CHALLENGE_NOT_FOUND",
  CHALLENGE_ALREADY_COMPLETED = "CHALLENGE_ALREADY_COMPLETED",

  // Generic
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}
